spring:
  datasource:
    url: jdbc:postgresql://localhost/alltalk
    username: alltalk_user
    password: alltalk4682

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "secret"
            client-secret: "secret"
